"""
Django settings for the OWASP Top 10:2025 Black-Box Practice Lab.

This app is intentionally vulnerable in specific, documented places
(see /instructor_solutions). Every OTHER part of the platform should be
built as securely as reasonably possible, so that unintended bugs do not
create accidental extra vulnerabilities. See section 8 of the build spec.
"""

from pathlib import Path
import os
import secrets

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Per-installation instance config (seed, secret key). Generated by run.sh
# on first run into instance_config.env. Never committed to git.
# ---------------------------------------------------------------------------
INSTANCE_CONFIG_PATH = BASE_DIR / "instance_config.env"


def _load_instance_config():
    values = {}
    if INSTANCE_CONFIG_PATH.exists():
        for line in INSTANCE_CONFIG_PATH.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()
    return values


def _write_instance_config(values):
    lines = [f"{k}={v}" for k, v in values.items()]
    INSTANCE_CONFIG_PATH.write_text("\n".join(lines) + "\n")


_instance = _load_instance_config()
_changed = False

if "LAB_SEED" not in _instance:
    _instance["LAB_SEED"] = secrets.token_hex(32)
    _changed = True

if "DJANGO_SECRET_KEY" not in _instance:
    _instance["DJANGO_SECRET_KEY"] = secrets.token_urlsafe(50)
    _changed = True

if _changed:
    _write_instance_config(_instance)

LAB_SEED = _instance["LAB_SEED"]
SECRET_KEY = _instance["DJANGO_SECRET_KEY"]

# ---------------------------------------------------------------------------
# Core Django settings
# ---------------------------------------------------------------------------
DEBUG = os.environ.get("LAB_DEBUG", "0") == "1"

ALLOWED_HOSTS = ["*"]  # single-user local instance, not internet-exposed

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "shop",
    "cart",
    "orders",
    "reviews",
    "sellerpanel",
    "support",
    "lab",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.RememberMeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "lab.context_processors.lab_progress",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 6}},
]

LANGUAGE_CODE = "uz"
TIME_ZONE = "Asia/Tashkent"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "shop:home"
LOGOUT_REDIRECT_URL = "shop:home"

# Where the "internal" services live for the SSRF scenario (A01).
# A real deployment would have real internal services; here it is a Django
# view namespace that is only reachable server-side / by direct URL guessing.
INTERNAL_SERVICE_BASE = "http://127.0.0.1:{port}"
