# Generated by Django 6.1 on 2026-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('secret', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=64, unique=True)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_flag', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HintUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=64)),
                ('level', models.PositiveSmallIntegerField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('vuln_id', 'level')},
            },
        ),
    ]
