"""
Deterministic, per-installation flag derivation.

Each install gets a random LAB_SEED (see config/settings.py, generated by
run.sh into instance_config.env, never committed to git). Every flag is
HMAC-SHA256(seed, vuln_id), truncated and formatted as FLAG{...}. This means:

- Flags differ between installations, so they cannot be shared/looked up.
- Flags cannot be produced without knowing the seed (server-side secret).
- Flags cannot be brute-forced from the frontend: they are computed on
  demand server-side and never rendered anywhere except as the direct,
  deliberate payload of a successful exploit (see each app's views.py).
"""

import hashlib
import hmac

from django.conf import settings

# The fixed, documented list of vulnerability IDs. Keep in sync with
# lab/vulnerabilities.py and instructor_solutions/.
VULN_IDS = [
    "A01-BAC-IDOR",
    "A01-BAC-SSRF",
    "A02-MISCONFIG",
    "A03-SUPPLYCHAIN",
    "A04-CRYPTO",
    "A05-INJECTION",
    "A06-INSECURE-DESIGN",
    "A07-AUTH",
    "A08-INTEGRITY",
    "A09-LOGGING",
    "A10-EXCEPTIONS",
]


def compute_flag(vuln_id: str) -> str:
    if vuln_id not in VULN_IDS:
        raise ValueError(f"Unknown vuln_id: {vuln_id}")
    digest = hmac.new(
        key=bytes.fromhex(settings.LAB_SEED),
        msg=vuln_id.encode("utf-8"),
        digestmod=hashlib.sha256,
    ).hexdigest()
    token = digest[:20]
    return f"FLAG{{{token}}}"
