"""
=== INTENTIONAL VULNERABILITY: A02:2025 - Security Misconfiguration ===
See instructor_solutions/A02-MISCONFIG.md

robots.txt "Disallow"s a path, which most crawlers respect but which is
NOT an access control mechanism - the path is still served to anyone who
requests it directly. It looks like a leftover ops backup left reachable
after a deploy.
"""

from django.http import HttpResponse

from .flags import compute_flag


def robots_txt(request):
    content = "User-agent: *\nDisallow: /internal-backup/\nDisallow: /lab/internal/\n"
    return HttpResponse(content, content_type="text/plain")


def internal_backup(request):
    flag = compute_flag("A02-MISCONFIG")
    content = (
        "# nightly-backup.sh - vega-market prod db dump (TEMP - REMOVE BEFORE DEPLOY)\n"
        "# generated by ops, forgot to delete from static hosting\n"
        f"# debug-note: leftover admin recovery token = {flag}\n"
        "# --- end of file ---\n"
    )
    return HttpResponse(content, content_type="text/plain")
